name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.4
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.8.4
  rxdart: 0.27.7

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
